# Generated by Django 6.0.5 on 2026-06-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('domestic', 'Domestic Transfer'), ('wire', 'Wire Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
