# Generated by Django 6.0.5 on 2026-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecuritysettings',
            name='otp_enabled',
            field=models.BooleanField(default=True, help_text="Require OTP verification for this user's transfers"),
        ),
    ]
