# Generated by Django 6.0.5 on 2026-06-12 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_accountrestriction_otp_vfn'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_approval_enabled', models.BooleanField(default=False, help_text="Require admin approval for this user's transfers")),
                ('otp_enabled', models.BooleanField(default=False, help_text="Require OTP verification for this user's transfers")),
                ('vfn_enabled', models.BooleanField(default=False, help_text="Require VFN code for this user's transfers")),
                ('is_restricted', models.BooleanField(default=False, help_text='Restrict this user from making transfers')),
                ('restriction_reason', models.TextField(blank=True, help_text='Reason for restriction (shown to user)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Security Setting',
                'verbose_name_plural': 'User Security Settings',
            },
        ),
    ]
