# Generated by Django 6.0.5 on 2026-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersecuritysettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VFN',
            new_name='IMF',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='vfn_enabled',
        ),
        migrations.RemoveField(
            model_name='usersecuritysettings',
            name='vfn_enabled',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imf_enabled',
            field=models.BooleanField(default=False, help_text='Require IMF code for transfers'),
        ),
        migrations.AddField(
            model_name='usersecuritysettings',
            name='imf_enabled',
            field=models.BooleanField(default=False, help_text="Require IMF code for this user's transfers"),
        ),
    ]
