# Generated by Django 6.0.5 on 2026-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_vfn_imf_remove_systemsettings_vfn_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecuritysettings',
            name='manual_verification_enabled',
            field=models.BooleanField(default=False, help_text='Require manual verification after transfer (receipt shows pending)'),
        ),
    ]
