# Generated by Django 6.0.5 on 2026-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersecuritysettings_manual_verification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='equivalent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
